// Generated by 'github.com/momchil-atanasov/gostub'

package acceptance_stubs

import (
	alias1 "github.com/momchil-atanasov/gostub/acceptance"
)

type EmptyInterfaceStub struct {
	StubGUID int
}

var _ alias1.EmptyInterface = new(EmptyInterfaceStub)
